# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls
          
          rm -f *.zip # Use -f to ignore errors if the zip doesn't exist
          zip -r cpu_hog_killer_v1.7.zip *

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.7
          release_name: Release v1.7
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cpu_hog_killer_v1.7.zip
          asset_name: cpu_hog_killer_v1.7.zip
          asset_content_type: application/zip
