name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Removing the current zip…
          rm -f cpu_hog_killer_v1.7.zip
          echo Creating a new zip release file…
          zip -r cpu_hog_killer_v1.7.zip *

      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: cpu_hog_killer_v1.7.zip
          path: cpu_hog_killer_v1.7.zip
